Tic tac toe
rosalogia/rucs24-bot pull request #12
Opened 2020-08-30 22:52 UTC by IshaanIvaturi

I added a TicTacToe Cog which contains a method (!tictactoe) that allows the user to play tic tac toe against an unbeatable AI using the minimax algorithm

2020-08-30 23:43 UTC, rosalogia requested changes
I think the code is quality and well-commented, but I think every part of the functionality being a nested function kind of hurts readability and obfuscates the way that the actual command works. Maybe that's just a personal thing, we can talk about it, but as I see it this would be more readable and clean if the nested functions were top-level functions that took the board as a parameter. I think the actual command function being very clean and simple, just a few function calls, would be ideal. If you're confused as to what I mean, I can show you. It shouldn't be more than a quick refactor.

2020-08-30 23:43 UTC, rosalogia commented on cogs/tictactoecog.py
> +            if len(valid_moves()) == 0:
You don't need an if statement here, you can just `return len(valid_moves()) == 0`

2020-08-30 23:48 UTC, IshaanIvaturi commented
Aight I can fix the if statement thing (just a mistake from fast code) and also yea I'll just move all the functions outside, I had it like that initially but later decided it might be better if it was self contained

2020-08-30 23:55 UTC, rosalogia commented
It might have been better like this if the tic tac toe cog didn't have it's own file, but since it does, it's not particularly messy to keep all the functions separately defined 👍

2020-08-31 00:48 UTC, rosalogia commented
Final request on my behalf: please use docstrings under function names to document how they work as opposed to single line comments above function names. Thank you!

2020-08-31 01:04 UTC, rosalogia approved these changes

2020-08-31 01:04 UTC, merged